require("tool.List")
require("tool.Dic")
print(1)
local k = {1, 2}
local list = List:New()
list:Add("kl")
list:Add("df")
list:Find()
list:Remove("df")
print(list:Count())
print(list[1])
print(list:Contains("df"))

local dic = Dictionary:New()
dic:Add("sss", 11)
dic:Add("kkk", 222)
print(dic:Count())
print(dic["sss"])
dic:Remove("kkk")
print(dic:ContainsKey("kkk"))
